const productos=[
    {
        id:1,
        productName:"Banana",
        price:480,
        quantity:1,
        img:'/images/banana.png'
    },
    {
        id:2,
        productName:"Leche",
        price:950,
        quantity:1,
        img:"/images/leche.png"
    },
    {
        id:3,
        productName:"Pollo",
        price:750,
        quantity:1,
        img:"/images/pollo.png"
    },
    {
        id:4,
        productName:"Mayonesa",
        price:510,
        quantity:1,
        img:"/images/mayonesa.png"
    }

];