const products = [
  {
    id: 1,
    band: "Spock's Beard",
    record: 'Octane',
    price: 1000,
    stock: 10,
    image: './media/2005 - Octane 01.jpg',
  },
  {
    id: 2,
    band: 'Anna Popovich',
    record: 'Still Making History',
    price: 900,
    stock: 12,
    image: './media/2007 - Still Making History 01.jpg',
  },
  {
    id: 3,
    band: 'Haken',
    record: 'The Mountain',
    price: 1200,
    stock: 20,
    image: './media/2013 - The Mountain 01.jpg',
  },
  {
    id: 4,
    band: 'Astor Piazzolla',
    record: 'Adios Nonino',
    price: 1300,
    stock: 14,
    image: './media/astor.jpg',
  },
  {
    id: 5,
    band: 'Carlos Del Junco',
    record: 'Big Boy',
    price: 2200,
    stock: 19,
    image: './media/bigboy.jpg',
  },
  {
    id: 6,
    band: 'Max Richter',
    record: 'Infra',
    price: 3400,
    stock: 8,
    image: './media/max.jpg',
  },
  {
    id: 7,
    band: 'Hiromi Uehara',
    record: 'Voice',
    price: 1800,
    stock: 18,
    image: './media/hiromi-voice.jpg',
  },
  {
    id: 8,
    band: 'Philip Glass',
    record: 'Glassworks',
    price: 2200,
    stock: 24,
    image: './media/philipglass.jpg',
  },
  {
    id: 9,
    band: 'Aerosmith',
    record: 'Toys in the Attic',
    price: 600,
    stock: 6,
    image: './media/toys in the attic front.jpg',
  },
  {
    id: 10,
    band: 'Flying Colors',
    record: 'Flying Colors',
    price: 1800,
    stock: 14,
    image: './media/flyingColors.jpg',
  },
  {
    id: 11,
    band: 'Diablo Swing Orchestra',
    record: "The Butcher's Ballroom",
    price: 3300,
    stock: 20,
    image: './media/diablo.jpg',
  },
  {
    id: 12,
    band: 'Chick Corea',
    record: 'Fiesta',
    price: 2100,
    stock: 12,
    image: './media/fiesta.jpg',
  },
];
